WQIT_proj/WQIT_proj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from app_wqit import views

urlpatterns = [
    url(r'^',include('app_wqit.urls')),
    url(r'^about/',include('app_wqit.urls')),
    path('admin/', admin.site.urls),
]

WQIT_proj/app_wqit/urls.py
from django.conf.urls import url
from app_wqit import views

#TEMPLATE TAGGING
app_name = "app_wqit"

urlpatterns = [
    url(r'^$',views.LandingView.as_view(),name='landing'),
    url(r'^index',views.QuoteListView.as_view(),name='index'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
]

WQIT_proj/app_wqit/models.py
from django.db import models


class Person(models.Model):
    person_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=264,unique=True)
    image_url = models.URLField(unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote_text = models.CharField(max_length=264,unique=True)
    quote_source = models.ForeignKey(Person,on_delete=models.CASCADE)

    def __str__(self):
        return self.quote_text

WQIT_proj/app_wqit/views.py
from app_wqit.models import Quote
from django.views.generic import TemplateView,ListView


class QuoteListView(ListView):
    model = Quote
    template_name = 'app_wqit/index.html'

class AboutView(TemplateView):
    template_name = 'app_wqit/about.html'

class LandingView(TemplateView):
    template_name = 'app_wqit/landing.html'

WQIT_proj/templates/app_wqit/about.html
<!DOCTYPE html>
{% extends "app_wqit/base.html" %}
  {% block body_block %}
    <h1 class="mt-4">THIS IS THE ABOUT PAGE!</h1>
    <div class="container mt-10" id="about-text">
      <h1 style="font-size: 7rem;">Hello, friend!</h1>
    <p>
    	Hope you're having a good time.
    </p>
    <hr>
    <p>
    	<br>We all want to be successful.
      	<br>And each of us has an individual definition of success.
      	<br>Mine is the ammount of positive impact I make on the lives of others.
      	<br>I believe I am still able to positively influence people's lives.
      	<br>Therefore, I haven't lived up to my potential.
  	</p>
  	<p>
  		<br>If any any of those quotes made you want to go out there and chase
      <br>your dreams- let me know about it.
  		<br>You are more than welcome to contact me on noamdvir123@gmail.com
  		<br>I'm super responsive. Try me!
  	</p>

    </div>
    {% endblock %}

WQIT_proj/templates/app_wqit/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Whose Quote Is This?</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Tangerine:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "css/myStyle.css" %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg  fixed-top">
      <span class="navbar-brand">Whose Quote Is This? </span>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'app_wqit:index' %}">Play</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'app_wqit:about' %}">About</a>
          </li>
        </ul>
      </div>
    </nav>

      {% block body_block %}
      {% endblock %}

  </body>
</html>

WQIT_proj/templates/app_wqit/index.html
<!DOCTYPE html>
{% extends "app_wqit/base.html" %}
{% load staticfiles %}
  {% block body_block %}

    <div class="container-fluid text-center fixed-top" id="jumbo">
      <p id="quote-container"></p>
      <p>
        <a class="btn btn-primary btn-md fast-transition shadow-none" id="reset" role="button" href="#">Reset</a>
        <a class="btn btn-primary btn-md fast-transition shadow-none" id="easy" role="button" href="#">Easy</a>
        <a class="btn btn-primary btn-md fast-transition selected shadow-none" id="hard" role="button" href="#">Hard</a>
      </p>
    </div>

    <div class="container-fluid" id="gallery">
       <div class="container-fluid" id="cards-cont">
            <div class="row justify-content-around" id="row_div_1">
                <div class="col-xs-12 col-md-6 col-lg-4">
                    <div class="card fast-transition mx-4">
                        <a href="#" class="d-none d-sm-block h-100">
                            <img class="card-img-top img-fluid img-thumbnail" src="#" alt="">
                        </a>
                        <div class="card-footer container-fluid" id="footerDiv">
                          <small class="text-muted">quoter option #1</small>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-6 col-lg-4">
                  <div class="card fast-transition mx-4">
                      <a href="#" class="d-none d-sm-block h-100">
                        <img class="card-img-top img-fluid img-thumbnail" src="#" alt="">
                      </a>
                      <div class="card-footer container-fluid" id="footerDiv">
                        <small class="text-muted">quoter option #2</small>
                      </div>
                  </div>
                </div>
                <div class="col-xs-12 col-md-6 col-lg-4">
                    <div class="card fast-transition mx-4">
                        <a href="#" class="d-none d-sm-block h-100">
                            <img class="card-img-top img-fluid img-thumbnail" src="#" alt="">
                        </a>
                        <div class="card-footer container-fluid" id="footerDiv">
                          <small class="text-muted">quoter option #3</small>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-6 col-lg-4">
                  <div class="card fast-transition mx-4">
                      <a href="#" class="d-none d-sm-block h-100">
                          <img class="card-img-top img-fluid img-thumbnail" src="#" alt="">
                      </a>
                      <div class="card-footer container-fluid" id="footerDiv">
                        <small class="text-muted">quoter option #4</small>
                      </div>
                  </div>
                </div>
                <div class="col-xs-12 col-md-6 col-lg-4">
                  <div class="card fast-transition mx-4">
                      <a href="#" class="d-none d-sm-block h-100">
                        <img class="card-img-top img-fluid img-thumbnail" src="#" alt="">
                      </a>
                      <div class="card-footer container-fluid" id="footerDiv">
                        <small class="text-muted">quoter option #5</small>
                      </div>
                  </div>
                </div>
                <div class="col-xs-12 col-md-6 col-lg-4">
                    <div class="card fast-transition mx-4">
                        <a href="#" class="d-none d-sm-block h-100">
                          <img class="card-img-top img-fluid img-thumbnail" src="#" alt="">
                        </a>
                        <div class="card-footer container-fluid" id="footerDiv">
                          <small class="text-muted">quoter option #6</small>
                        </div>
                    </div>
                </div>
            </div>
       </div>
    </div>
    <script type="text/javascript">
      var my_quotes = []
      var my_quotes_sources = []
      var img_urls = []
        {% for quote in quote_list %}
            my_quotes.push("{{ quote.quote_text }}")
            my_quotes_sources.push("{{ quote.quote_source }}")
            img_urls.push("{{ quote.quote_source.image_url }}")
        {% endfor %}
    </script>

    <script type="text/javascript" src="{% static "JavaScript/JS_wqit.js" %}">
    </script>

  {% endblock %}

WQIT_proj/templates/app_wqit/landing.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>Whose Quote Is This?</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<link href="https://fonts.googleapis.com/css?family=Play:400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static "css/landing.css" %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" type="text/javascript" async></script>
</head>
<body>
	<div id="landing-header">
 		<h1>Welcome to 'Whose Quote Is This?'</h1>
 		<p>
 			<br>Whether you're looking for a cool phrase to tattoo on your body
			<br>or simply appreciate a powerful quote from unique individuals
			<br>WQIT is the place for you
 		</p>
		<a href="{% url 'app_wqit:index' %}" class="btn btn-lg" id="play-btn">Let's play</a>
    </div>
    <ul class="slideshow">
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
    </ul>
</body>
</html>